<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Domain\Esyasoft.Ldap.Gateway.Domain.csproj" />
    <ProjectReference Include="..\Infrastructure\Esyasoft.Ldap.Gateway.Infrastructure.csproj" />
    <ProjectReference Include="..\Infrastructure\Esyasoft.Ldap.Gateway.Infrastructure.csproj" />
  </ItemGroup>

</Project>
